
# html lang
language: zh-Hans
# main menu navigation
menu:
  home: /
  archives: /archives
  categories: /categories  
  tags: /tags
  search: /search
  about: /about
  rss: /atom.xml

# Miscelaneous
favicon: /images/logo.png
#https://ws1.sinaimg.cn/large/005RGBbLly1fxjm6hz9yyj30cs0csdnk.jpg


# stylesheets loaded in the <head>
stylesheets:
# - /css/normalize.css
- //cdn.bootcss.com/pure/1.0.0/pure-min.css
- /css/xoxo.css

# scripts loaded in the end of the body
scripts:
#- //cdn.bootcss.com/zepto/1.2.0/zepto.min.js
#- /js/xoxo.js

# switch
show_excerpt: true
show_date: true
#footer
index_page: https://hjwjw.github.io
main_site: https://hjwjw.github.io
github: https://github.com/hjwjw
